---
repos:
  - pulibrary/abid
  - pulibrary/dpul
  - pulibrary/dpul-collections
  - pulibrary/figgy
  - pulibrary/imagecat-rails
  - pulibrary/lae-blacklight
  - pulibrary/pulmap
  - pulibrary/pulfalight